# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chord_service.proto',
  package='chordService',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63hord_service.proto\x12\x0c\x63hordService\"3\n\x14\x46indSuccessorRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07pathlen\x18\x02 \x01(\x05\"K\n\x15\x46indSuccessorResponse\x12\x13\n\x0bsuccessorId\x18\x01 \x01(\x05\x12\x0f\n\x07pathlen\x18\x02 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\t\"\x17\n\x15GetPredecessorRequest\"2\n\x16GetPredecessorResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"4\n\rNotifyRequest\x12\x15\n\rpredecessorId\x18\x01 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\" \n\x0eNotifyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x17\n\x15GetFingerTableRequest\"\x8c\x01\n\x16GetFingerTableResponse\x12\x39\n\x05table\x18\x01 \x03(\x0b\x32*.chordService.GetFingerTableResponse.Entry\x1a\x37\n\x05\x45ntry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0csuccessor_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\t2\xec\x02\n\x05\x43hord\x12[\n\x0e\x66ind_successor\x12\".chordService.FindSuccessorRequest\x1a#.chordService.FindSuccessorResponse\"\x00\x12^\n\x0fget_predecessor\x12#.chordService.GetPredecessorRequest\x1a$.chordService.GetPredecessorResponse\"\x00\x12\x45\n\x06notify\x12\x1b.chordService.NotifyRequest\x1a\x1c.chordService.NotifyResponse\"\x00\x12_\n\x10get_finger_table\x12#.chordService.GetFingerTableRequest\x1a$.chordService.GetFingerTableResponse\"\x00\x62\x06proto3')
)




_FINDSUCCESSORREQUEST = _descriptor.Descriptor(
  name='FindSuccessorRequest',
  full_name='chordService.FindSuccessorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chordService.FindSuccessorRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pathlen', full_name='chordService.FindSuccessorRequest.pathlen', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=88,
)


_FINDSUCCESSORRESPONSE = _descriptor.Descriptor(
  name='FindSuccessorResponse',
  full_name='chordService.FindSuccessorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='successorId', full_name='chordService.FindSuccessorResponse.successorId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pathlen', full_name='chordService.FindSuccessorResponse.pathlen', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='chordService.FindSuccessorResponse.addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=165,
)


_GETPREDECESSORREQUEST = _descriptor.Descriptor(
  name='GetPredecessorRequest',
  full_name='chordService.GetPredecessorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=190,
)


_GETPREDECESSORRESPONSE = _descriptor.Descriptor(
  name='GetPredecessorResponse',
  full_name='chordService.GetPredecessorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chordService.GetPredecessorResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='chordService.GetPredecessorResponse.addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=242,
)


_NOTIFYREQUEST = _descriptor.Descriptor(
  name='NotifyRequest',
  full_name='chordService.NotifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predecessorId', full_name='chordService.NotifyRequest.predecessorId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='chordService.NotifyRequest.addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=296,
)


_NOTIFYRESPONSE = _descriptor.Descriptor(
  name='NotifyResponse',
  full_name='chordService.NotifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='chordService.NotifyResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=330,
)


_GETFINGERTABLEREQUEST = _descriptor.Descriptor(
  name='GetFingerTableRequest',
  full_name='chordService.GetFingerTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=355,
)


_GETFINGERTABLERESPONSE_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='chordService.GetFingerTableResponse.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='chordService.GetFingerTableResponse.Entry.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='successor_id', full_name='chordService.GetFingerTableResponse.Entry.successor_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='chordService.GetFingerTableResponse.Entry.addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=498,
)

_GETFINGERTABLERESPONSE = _descriptor.Descriptor(
  name='GetFingerTableResponse',
  full_name='chordService.GetFingerTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='chordService.GetFingerTableResponse.table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETFINGERTABLERESPONSE_ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=498,
)

_GETFINGERTABLERESPONSE_ENTRY.containing_type = _GETFINGERTABLERESPONSE
_GETFINGERTABLERESPONSE.fields_by_name['table'].message_type = _GETFINGERTABLERESPONSE_ENTRY
DESCRIPTOR.message_types_by_name['FindSuccessorRequest'] = _FINDSUCCESSORREQUEST
DESCRIPTOR.message_types_by_name['FindSuccessorResponse'] = _FINDSUCCESSORRESPONSE
DESCRIPTOR.message_types_by_name['GetPredecessorRequest'] = _GETPREDECESSORREQUEST
DESCRIPTOR.message_types_by_name['GetPredecessorResponse'] = _GETPREDECESSORRESPONSE
DESCRIPTOR.message_types_by_name['NotifyRequest'] = _NOTIFYREQUEST
DESCRIPTOR.message_types_by_name['NotifyResponse'] = _NOTIFYRESPONSE
DESCRIPTOR.message_types_by_name['GetFingerTableRequest'] = _GETFINGERTABLEREQUEST
DESCRIPTOR.message_types_by_name['GetFingerTableResponse'] = _GETFINGERTABLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindSuccessorRequest = _reflection.GeneratedProtocolMessageType('FindSuccessorRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDSUCCESSORREQUEST,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.FindSuccessorRequest)
  ))
_sym_db.RegisterMessage(FindSuccessorRequest)

FindSuccessorResponse = _reflection.GeneratedProtocolMessageType('FindSuccessorResponse', (_message.Message,), dict(
  DESCRIPTOR = _FINDSUCCESSORRESPONSE,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.FindSuccessorResponse)
  ))
_sym_db.RegisterMessage(FindSuccessorResponse)

GetPredecessorRequest = _reflection.GeneratedProtocolMessageType('GetPredecessorRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPREDECESSORREQUEST,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.GetPredecessorRequest)
  ))
_sym_db.RegisterMessage(GetPredecessorRequest)

GetPredecessorResponse = _reflection.GeneratedProtocolMessageType('GetPredecessorResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPREDECESSORRESPONSE,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.GetPredecessorResponse)
  ))
_sym_db.RegisterMessage(GetPredecessorResponse)

NotifyRequest = _reflection.GeneratedProtocolMessageType('NotifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYREQUEST,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.NotifyRequest)
  ))
_sym_db.RegisterMessage(NotifyRequest)

NotifyResponse = _reflection.GeneratedProtocolMessageType('NotifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYRESPONSE,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.NotifyResponse)
  ))
_sym_db.RegisterMessage(NotifyResponse)

GetFingerTableRequest = _reflection.GeneratedProtocolMessageType('GetFingerTableRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETFINGERTABLEREQUEST,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.GetFingerTableRequest)
  ))
_sym_db.RegisterMessage(GetFingerTableRequest)

GetFingerTableResponse = _reflection.GeneratedProtocolMessageType('GetFingerTableResponse', (_message.Message,), dict(

  Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
    DESCRIPTOR = _GETFINGERTABLERESPONSE_ENTRY,
    __module__ = 'chord_service_pb2'
    # @@protoc_insertion_point(class_scope:chordService.GetFingerTableResponse.Entry)
    ))
  ,
  DESCRIPTOR = _GETFINGERTABLERESPONSE,
  __module__ = 'chord_service_pb2'
  # @@protoc_insertion_point(class_scope:chordService.GetFingerTableResponse)
  ))
_sym_db.RegisterMessage(GetFingerTableResponse)
_sym_db.RegisterMessage(GetFingerTableResponse.Entry)



_CHORD = _descriptor.ServiceDescriptor(
  name='Chord',
  full_name='chordService.Chord',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=501,
  serialized_end=865,
  methods=[
  _descriptor.MethodDescriptor(
    name='find_successor',
    full_name='chordService.Chord.find_successor',
    index=0,
    containing_service=None,
    input_type=_FINDSUCCESSORREQUEST,
    output_type=_FINDSUCCESSORRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_predecessor',
    full_name='chordService.Chord.get_predecessor',
    index=1,
    containing_service=None,
    input_type=_GETPREDECESSORREQUEST,
    output_type=_GETPREDECESSORRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='notify',
    full_name='chordService.Chord.notify',
    index=2,
    containing_service=None,
    input_type=_NOTIFYREQUEST,
    output_type=_NOTIFYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_finger_table',
    full_name='chordService.Chord.get_finger_table',
    index=3,
    containing_service=None,
    input_type=_GETFINGERTABLEREQUEST,
    output_type=_GETFINGERTABLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHORD)

DESCRIPTOR.services_by_name['Chord'] = _CHORD

# @@protoc_insertion_point(module_scope)
