# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chord_service_pb2 as chord__service__pb2


class ChordStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.find_successor = channel.unary_unary(
        '/chordService.Chord/find_successor',
        request_serializer=chord__service__pb2.FindSuccessorRequest.SerializeToString,
        response_deserializer=chord__service__pb2.FindSuccessorResponse.FromString,
        )
    self.get_predecessor = channel.unary_unary(
        '/chordService.Chord/get_predecessor',
        request_serializer=chord__service__pb2.GetPredecessorRequest.SerializeToString,
        response_deserializer=chord__service__pb2.GetPredecessorResponse.FromString,
        )
    self.notify_at_join = channel.unary_unary(
        '/chordService.Chord/notify_at_join',
        request_serializer=chord__service__pb2.NotifyRequest.SerializeToString,
        response_deserializer=chord__service__pb2.NotifyResponse.FromString,
        )
    self.notify_at_leave = channel.unary_unary(
        '/chordService.Chord/notify_at_leave',
        request_serializer=chord__service__pb2.NotifyRequest.SerializeToString,
        response_deserializer=chord__service__pb2.NotifyResponse.FromString,
        )
    self.check = channel.unary_unary(
        '/chordService.Chord/check',
        request_serializer=chord__service__pb2.CheckRequest.SerializeToString,
        response_deserializer=chord__service__pb2.CheckResponse.FromString,
        )
    self.get_configuration = channel.unary_unary(
        '/chordService.Chord/get_configuration',
        request_serializer=chord__service__pb2.GetConfigurationRequest.SerializeToString,
        response_deserializer=chord__service__pb2.GetConfigurationResponse.FromString,
        )
    self.get = channel.unary_unary(
        '/chordService.Chord/get',
        request_serializer=chord__service__pb2.GetRequest.SerializeToString,
        response_deserializer=chord__service__pb2.GetResponse.FromString,
        )
    self.put = channel.unary_unary(
        '/chordService.Chord/put',
        request_serializer=chord__service__pb2.PutRequest.SerializeToString,
        response_deserializer=chord__service__pb2.PutResponse.FromString,
        )


class ChordServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def find_successor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_predecessor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def notify_at_join(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def notify_at_leave(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_configuration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChordServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'find_successor': grpc.unary_unary_rpc_method_handler(
          servicer.find_successor,
          request_deserializer=chord__service__pb2.FindSuccessorRequest.FromString,
          response_serializer=chord__service__pb2.FindSuccessorResponse.SerializeToString,
      ),
      'get_predecessor': grpc.unary_unary_rpc_method_handler(
          servicer.get_predecessor,
          request_deserializer=chord__service__pb2.GetPredecessorRequest.FromString,
          response_serializer=chord__service__pb2.GetPredecessorResponse.SerializeToString,
      ),
      'notify_at_join': grpc.unary_unary_rpc_method_handler(
          servicer.notify_at_join,
          request_deserializer=chord__service__pb2.NotifyRequest.FromString,
          response_serializer=chord__service__pb2.NotifyResponse.SerializeToString,
      ),
      'notify_at_leave': grpc.unary_unary_rpc_method_handler(
          servicer.notify_at_leave,
          request_deserializer=chord__service__pb2.NotifyRequest.FromString,
          response_serializer=chord__service__pb2.NotifyResponse.SerializeToString,
      ),
      'check': grpc.unary_unary_rpc_method_handler(
          servicer.check,
          request_deserializer=chord__service__pb2.CheckRequest.FromString,
          response_serializer=chord__service__pb2.CheckResponse.SerializeToString,
      ),
      'get_configuration': grpc.unary_unary_rpc_method_handler(
          servicer.get_configuration,
          request_deserializer=chord__service__pb2.GetConfigurationRequest.FromString,
          response_serializer=chord__service__pb2.GetConfigurationResponse.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=chord__service__pb2.GetRequest.FromString,
          response_serializer=chord__service__pb2.GetResponse.SerializeToString,
      ),
      'put': grpc.unary_unary_rpc_method_handler(
          servicer.put,
          request_deserializer=chord__service__pb2.PutRequest.FromString,
          response_serializer=chord__service__pb2.PutResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chordService.Chord', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
